# OUTPUT_LANG_INDEX start from 0
generator-localization-pe-admin:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1drnC7jFf6YzWZMNScVbjjGH8u7LEXkEMf2i0gatMKvI GID_ID=pe-admin-localization OUTPUT_FOLDER=../src/i18n/locales/en/defaults.json

